# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "615d2016ebd550d3dfa37e06ac3d8074"
name = " Kakao AlimTalk (Local)"
handle = "kakao-alimtalk-live"
application_url = "https://judicial-barcelona-units-virtually.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tlx-new-brand.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_fulfillments,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://judicial-barcelona-units-virtually.trycloudflare.com/auth/callback",
  "https://judicial-barcelona-units-virtually.trycloudflare.com/auth/shopify/callback",
  "https://judicial-barcelona-units-virtually.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
